### PR TITLE
Kb spacy

### PR DESCRIPTION
**Pull request by kasparvonbeelen**

### CODE REVIEW

**Comment by mcollardanuy** [comment]
Hi Kaspar!

All good, but there's a few broken links/exercises:
* [4b-Intro-to-NLP](https://github.com/Living-with-machines/dhoxss-text2tech/blob/kb-spacy/Sessions/4b-Intro-to-NLP.ipynb): typo: "a pipelines" 
* [4c-Intro-to-NLP](https://github.com/Living-with-machines/dhoxss-text2tech/blob/kb-spacy/Sessions/4c-Intro-to-NLP.ipynb): "First let's have a look at our data [here](https://github.com/Living-with-machines/dhoxss-text2tech/blob/kb-spacy/Sessions/data/LwM-nlp-animacy-annotations-machines19thC.tsv)." --> The link is broken, it points to an old tsv.
* [4c-Intro-to-NLP](https://github.com/Living-with-machines/dhoxss-text2tech/blob/kb-spacy/Sessions/4c-Intro-to-NLP.ipynb): In the last exercise, I think you need to change `SentenceCtxt` to `TextSnippet` (both in the exercise and the solution).
* [4d-Intro-to-NLP](https://github.com/Living-with-machines/dhoxss-text2tech/blob/kb-spacy/Sessions/4d-Intro-to-NLP.ipynb): Better remove the "Disambiguation" both in the title and the content of the first cell, since it's not covered?
* [4d-Intro-to-NLP](https://github.com/Living-with-machines/dhoxss-text2tech/blob/kb-spacy/Sessions/4d-Intro-to-NLP.ipynb): The exercise is using the animacy dataset but only the bl books dataset has been loaded. So maybe better to change the exercise to apply the function to the `text` column of the `clean_blbooks_df` dataframe?

**Comment by kasparvonbeelen** [comment]
Hi Mariona!

Thanks so much for these detailed suggestions! I should have fixed these in the latest commit, but will double check :-)

**Comment by kasparvonbeelen** [comment]
Tried to improve these notebooks a bit more. I hope it's ready to merge :-)

**Review by mcollardanuy — APPROVED** [review]
Hi @kasparvonbeelen, all good!

**Comment by kasparvonbeelen** [comment]
Thanks! Merged!

**Pull request merged**
