### PR TITLE
Static word embeddings

### PR DESCRIPTION
**Pull request by mcollardanuy**

### CODE REVIEW

**Comment by kasparvonbeelen** [comment]
Looking good, made a few comments on the notebooks in ReviewNB. Hopefully you can see it there?

**Comment by mcollardanuy** [comment]
Thanks, fixed!

**Comment by mcollardanuy** [comment]
Hi @kasparvonbeelen, all fixed!

**Review by kasparvonbeelen — COMMENTED** [review]
All good!

**Review by kasparvonbeelen — APPROVED** [review]

**Pull request merged**
