### PR TITLE
Lms

### PR DESCRIPTION
**Pull request by kasparvonbeelen**

### CODE REVIEW

**Comment by kallewesterling** [comment]
@kasparvonbeelen Do you think I can merge this into the `dev` branch? I'm going through legacy work for LwM and merging pending PRs is part of the process.

**Comment by kasparvonbeelen** [comment]
Hi @kallewesterling I think the dev branch was final, so I wouldn't merge these pending PR for this repo.

**Comment by kallewesterling** [comment]
OK, thanks @kasparvonbeelen -- do you think we should just close this PR then?

**Comment by kasparvonbeelen** [comment]
Yes, I thinks that should be fine.

**Pull request closed without merging**
